title: Jim Vernon Solutions Blog
author: jimvernonsolutions
email: jim@jimvernon.solutions
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is my practice in building a GitHub Pages site.  I want to build real sites.
  This is not real HTML/CSS, for example.  GitHub Pages is doing all the translating, but it's also not giving me a WYSIWYG editor.

# social links
twitter_username: carpeweb # DO NOT include the @ character, or else the build will fail! I need a new twitter handle!
github_username:  jimvernonsolutions # DO NOT include the @ character, or else the build will fail! I should add a twitter account for jvs!

show_excerpts: true # set to false to remove excerpts on the homepage
